export const REQUEST_POSTS = 'REQUEST_POSTS'
export const SET_POSTS = 'SET_POSTS'

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_SORT_BY = 'SET_SORT_BY'

export const REQUEST_POST = 'REQUEST_POST'
export const SET_ACTIVE_POST = 'SET_ACTIVE_POST'
export const CREATE_POST = 'CREATE_POST'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'

export const INCREMENT_VOTE = 'INCREMENT_VOTE'
export const DECREMENT_VOTE = 'DECREMENT_VOTE'

export const REQUEST_COMMENTS_FOR_POST = 'REQUEST_COMMENTS_FOR_POST'
export const SET_COMMENTS_FOR_POST = 'SET_COMMENTS_FOR_POST'
