export const REQUEST_POSTS = 'REQUEST_POSTS'
export const SET_POSTS = 'SET_POSTS'

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_SORT_BY = 'SET_SORT_BY'

export const REQUEST_POST = 'REQUEST_POST'
export const UPDATE_ACTIVE_POST = 'UPDATE_ACTIVE_POST'
export const CREATE_POST = 'CREATE_POST'
export const BEGIN_POST_EDIT = 'BEGIN_POST_EDIT'
export const END_POST_EDIT = 'END_POST_EDIT'
export const SUBMIT_POST_EDIT = 'SUBMIT_POST_EDIT'
export const DELETE_POST = 'DELETE_POST'

export const CAST_VOTE_ON_POST = 'CAST_VOTE_ON_POST'
export const CAST_VOTE_ON_COMMENT = 'CAST_VOTE_ON_COMMENT'

export const REQUEST_COMMENTS_FOR_POST = 'REQUEST_COMMENTS_FOR_POST'
export const SET_ACTIVE_COMMENTS = 'SET_COMMENTS_FOR_POST'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const OPEN_NEW_COMMENT_DIALOG = 'OPEN_NEW_COMMENT_DIALOG'
export const CLOSE_NEW_COMMENT_DIALOG = 'CLOSE_NEW_COMMENT_DIALOG'
export const OPEN_EDIT_COMMENT_DIALOG = 'OPEN_EDIT_COMMENT_DIALOG'
export const CLOSE_EDIT_COMMENT_DIALOG = 'CLOSE_EDIT_COMMENT_DIALOG'
